### PR TITLE
Add cmsRecoGeom-2021.root to Geometry-DTGeometryBuilder 

### PR DESCRIPTION
**Pull request by slomeo**
Add cmsRecoGeom-2021.root to Geometry-DTGeometryBuilder in order to continue with PR #31043

### CODE REVIEW

**Comment by mrodozov** [comment]
I see you figure it. good :) it's exactly that

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
@mrodozov @smuzaffar Why does the unit test fail for this PR? I thought the PR is providing the file needed by the unit test.

**Comment by smuzaffar** [comment]
+externals
only new file, lets get this in IB

**Pull request merged**
